name: Build WebDriverAgentRunner IPA

on:
  workflow_dispatch:

jobs:
  build-wda:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode and import iOS Development certificate
        uses: apple/import-codesign-certs@v1
        with:
          p12-base64: ${{ secrets.APPLE_CERT_P12_BASE64 }}
          p12-password: ${{ secrets.APPLE_CERT_PASSWORD }}

      - name: Decode and install provisioning profile
        uses: apple/import-provisioning-profile@v1
        with:
          profile-base64: ${{ secrets.PROVISION_PROFILE_BASE64 }}

      - name: Build & Archive WebDriverAgentRunner
        run: |
          # 1) Clone the Appium-managed WebDriverAgent repository
          git clone https://github.com/appium/WebDriverAgent.git
          cd WebDriverAgent

          # 2) Initialize submodules
          git submodule update --init --recursive

          # 3) Archive (build) the Runner using Manual signing
          xcodebuild -project WebDriverAgent.xcodeproj \
            -scheme WebDriverAgentRunner \
            -configuration Release \
            -archivePath build/WDA.xcarchive \
            PROVISIONING_PROFILE_SPECIFIER="WDA-Custom-Profile" \
            CODE_SIGN_STYLE=Manual \
            clean archive

      - name: Export signed IPA
        run: |
          cd WebDriverAgent
          xcodebuild -exportArchive \
            -archivePath build/WDA.xcarchive \
            -exportPath build/out \
            -exportOptionsPlist Scripts/exportOptions.plist

      - name: Upload signed IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebDriverAgentRunner.ipa
          path: WebDriverAgent/build/out/WebDriverAgentRunner.ipa
