name: Build WebDriverAgentRunner IPA

on:
  workflow_dispatch:

jobs:
  build-wda:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Import iOS signing certificate
        uses: apple-actions/import-codesign-certs@v3
        with:
          # Must be exactly the Base-64 string of your .p12, no headers, no line breaks
          p12-file-base64: ${{ secrets.APPLE_CERT_P12_BASE64 }}
          # The passphrase you used when exporting that .p12
          p12-password: ${{ secrets.APPLE_CERT_PASSWORD }}

      - name: Install provisioning profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "${{ secrets.PROVISION_PROFILE_BASE64 }}" \
            | base64 --decode \
            > ~/Library/MobileDevice/Provisioning\ Profiles/WDA-Custom-Profile.mobileprovision
          ls -lh ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Clone & build WebDriverAgentRunner
        run: |
          git clone https://github.com/appium/WebDriverAgent.git
          cd WebDriverAgent
          git submodule update --init --recursive

          xcodebuild \
            -project WebDriverAgent.xcodeproj \
            -scheme WebDriverAgentRunner \
            -configuration Release \
            -archivePath build/WDA.xcarchive \
            PROVISIONING_PROFILE_SPECIFIER="WDA-Custom-Profile" \
            CODE_SIGN_STYLE=Manual \
            clean archive

      - name: Export signed IPA
        run: |
          cd WebDriverAgent
          xcodebuild -exportArchive \
            -archivePath build/WDA.xcarchive \
            -exportPath build/out \
            -exportOptionsPlist Scripts/exportOptions.plist

      - name: Upload signed IPA
        uses: actions/upload-artifact@v4
        with:
          name: WebDriverAgentRunner.ipa
          path: WebDriverAgent/build/out/WebDriverAgentRunner.ipa
