name: Build WebDriverAgentRunner IPA

on:
  workflow_dispatch:

jobs:
  build-wda:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode certificates & provisioning profile
        env:
          CERT_BASE64: ${{ secrets.APPLE_CERT_P12_BASE64 }}
          CERT_PW:   ${{ secrets.APPLE_CERT_PASSWORD }}
          PROFILE_BASE64: ${{ secrets.PROVISION_PROFILE_BASE64 }}
        run: |
          # Decode the Base64‐encoded P12 into a file
          echo "$CERT_BASE64" | base64 --decode > ios_dev.p12

          # Decode the Base64‐encoded provisioning profile into a file
          echo "$PROFILE_BASE64" | base64 --decode > WDA-Custom-Profile.mobileprovision

          # Sanity check: confirm both files exist and are non-zero
          ls -lh ios_dev.p12 WDA-Custom-Profile.mobileprovision

      - name: Import iOS Development certificate into the default login keychain
        run: |
          # On GitHub macOS runners, importing without "-k" automatically uses login.keychain-db
          # The Apple certificate passphrase is in $CERT_PW; "-A" grants all apps (codesign, xcodebuild) access.
          security import ios_dev.p12 \
            -P "$CERT_PW" \
            -T /usr/bin/codesign \
            -A

          # Verify that the iPhone Development identity now appears in the login keychain
          security find-identity -v -p codesigning

      - name: Copy provisioning profile into place
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp WDA-Custom-Profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/
          ls -lh ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build & Archive WebDriverAgentRunner
        run: |
          # 1) Clone the Appium‐maintained WebDriverAgent repository
          git clone https://github.com/appium/WebDriverAgent.git
          cd WebDriverAgent

          # 2) Pull all submodules (WebDriverAgent depends on several)
          git submodule update --init --recursive

          # 3) Archive (build) the Runner with your provisioning profile
          xcodebuild -project WebDriverAgent.xcodeproj \
            -scheme WebDriverAgentRunner \
            -configuration Release \
            -archivePath build/WDA.xcarchive \
            PROVISIONING_PROFILE_SPECIFIER="WDA-Custom-Profile" \
            CODE_SIGN_STYLE=Manual \
            clean archive

      - name: Export signed IPA
        run: |
          cd WebDriverAgent
          xcodebuild -exportArchive \
            -archivePath build/WDA.xcarchive \
            -exportPath build/out \
            -exportOptionsPlist Scripts/exportOptions.plist

      - name: Upload signed IPA as workflow artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebDriverAgentRunner.ipa
          path: WebDriverAgent/build/out/WebDriverAgentRunner.ipa
