name: Build WebDriverAgentRunner IPA

on:
  workflow_dispatch:

jobs:
  build-wda:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode and import iOS Development certificate
        uses: apple/actions-import-codesign-certs@v1
        with:
          p12-base64: ${{ secrets.APPLE_CERT_P12_BASE64 }}
          p12-password: ${{ secrets.APPLE_CERT_PASSWORD }}
        # This Action will:
        # 1) Decode the Base64 P12
        # 2) Create a temporary keychain, unlock it, import the P12
        # 3) Add the keychain to the search path so xcodebuild can find it

      - name: Decode and install provisioning profile
        uses: apple/actions-import-provisioning-profile@v1
        with:
          provisioning-profile-base64: ${{ secrets.PROVISION_PROFILE_BASE64 }}
        # This Action will:
        # 1) Decode the Base64 provisioning profile
        # 2) Copy it into ~/Library/MobileDevice/Provisioning Profiles/

      - name: Build & Archive WebDriverAgentRunner
        run: |
          # 1) Clone the official Appium-managed WebDriverAgent repo
          git clone https://github.com/appium/WebDriverAgent.git
          cd WebDriverAgent

          # 2) Initialize and update all submodules
          git submodule update --init --recursive

          # 3) Archive (build) the WDA Runner using Manual signing
          xcodebuild -project WebDriverAgent.xcodeproj \
            -scheme WebDriverAgentRunner \
            -configuration Release \
            -archivePath build/WDA.xcarchive \
            PROVISIONING_PROFILE_SPECIFIER="WDA-Custom-Profile" \
            CODE_SIGN_STYLE=Manual \
            clean archive

      - name: Export signed IPA
        run: |
          cd WebDriverAgent
          xcodebuild -exportArchive \
            -archivePath build/WDA.xcarchive \
            -exportPath build/out \
            -exportOptionsPlist Scripts/exportOptions.plist

      - name: Upload signed IPA as artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebDriverAgentRunner.ipa
          path: WebDriverAgent/build/out/WebDriverAgentRunner.ipa
