name: Build WDA IPA
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Decode cert & profile
        env:
          CERT:  ${{ secrets.APPLE_CERT_P12_BASE64 }}
          CERT_PW: ${{ secrets.APPLE_CERT_PASSWORD }}
          PROFILE: ${{ secrets.PROVISION_PROFILE_BASE64 }}
        run: |
          echo "$CERT"  | base64 --decode > signing.p12
          echo "$PROFILE" | base64 --decode > WDA.mobileprovision

      - name: Install cert
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security import signing.p12 -k build.keychain -P "$CERT_PW" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" build.keychain

      - name: Build IPA
        run: |
          xcodebuild -project WebDriverAgent.xcodeproj -scheme WebDriverAgentRunner \
            -configuration Release -archivePath build/WDA.xcarchive \
            PROVISIONING_PROFILE_SPECIFIER="WDA" \
            CODE_SIGN_STYLE=Manual \
            clean archive
          xcodebuild -exportArchive -archivePath build/WDA.xcarchive \
            -exportPath build/out -exportOptionsPlist Scripts/exportOptions.plist
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: WDA-ipa
          path: build/out/WebDriverAgentRunner.ipa
