name: Build WebDriverAgentRunner IPA

on:
  workflow_dispatch:

jobs:
  build-wda:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Decode certificates & provisioning profile
        env:
          CERT_BASE64: ${{ secrets.APPLE_CERT_P12_BASE64 }}
          CERT_PW:   ${{ secrets.APPLE_CERT_PASSWORD }}
          PROFILE_BASE64: ${{ secrets.PROVISION_PROFILE_BASE64 }}
        run: |
          echo "$CERT_BASE64"  | base64 --decode > ios_dev.p12
          echo "$PROFILE_BASE64" | base64 --decode > WDA-Custom-Profile.mobileprovision

      - name: Import iOS Dev certificate
        run: |
          security create-keychain -p "Kupa8284" wda.keychain
          security default-keychain -s wda.keychain
          security import ios_dev.p12 -k wda.keychain -P "$CERT_PW" -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple: -s -k "" wda.keychain

      - name: Copy provisioning profile into place
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp WDA-Custom-Profile.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build & Archive WDA
        run: |
          git clone https://github.com/appium/WebDriverAgent.git
          cd WebDriverAgent
          git submodule update --init --recursive
          xcodebuild -project WebDriverAgent.xcodeproj \
            -scheme WebDriverAgentRunner \
            -configuration Release \
            -archivePath build/WDA.xcarchive \
            PROVISIONING_PROFILE_SPECIFIER="WDA-Custom-Profile" \
            CODE_SIGN_STYLE=Manual \
            clean archive

      - name: Export IPA
        run: |
          cd WebDriverAgent
          xcodebuild -exportArchive \
            -archivePath build/WDA.xcarchive \
            -exportPath build/out \
            -exportOptionsPlist Scripts/exportOptions.plist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: WebDriverAgentRunner.ipa
          path: WebDriverAgent/build/out/WebDriverAgentRunner.ipa
